source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target '___PACKAGENAME___' do
	pod 'XCGLogger', '3.3'
	pod 'SwiftGen', '2.0.0'

	target '___PACKAGENAME___Tests' do

	end
end
